dropout: 0.3
encoder_type: dinov2
learning_rate: 0.0003
local_model_dir: src/pretrained_encoders/dinov2-small
num_classes: 18
position_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDgAAADk0MTQ3OTk0MzQ4MzUycQJYAwAAAGNwdXEDSxJOdHEEUS6AAl1xAFgOAAAAOTQx
    NDc5OTQzNDgzNTJxAWEuEgAAAAAAAAAAAKBA/P8fQAAAoEAAAKBAr8kmQAAAoED8/y1A0aNwQPz/
    LUBhOos/a9u2P/ESWkAAAKBAAACgQAAAoEBhZp5AAACgQAAAoEA=
- 0
- !!python/tuple
  - 18
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
